config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "billboards#index"

  resources :artists do 
    resources :songs
  end
  
  resources :billboards do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
    belongs_to :user
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
    belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard, optional: true
end

app/models/user.rb
class User < ApplicationRecord
 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :artists
  has_many :billboards
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
    def configure_permitted_paramters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @arts = current_user.artists
  end

  def show
  end

  def new
    @art = Artist.new
    render :template => "artists/_form"
  end

  def create
    @art = current_user.artists.new(artist_params)

    if @art.save
      redirect_to artists_path
    else
      render :new
    end
  end
  
  def edit
    render :template => "artists/_form"
  end

  def update
    if @art.update(artist_params)
      redirect_to artist_path(@art)
    else
      render :edit
    end
  end

  def destroy
    @art.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @art = current_user.artists.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:artist_name)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billb, only: [:show, :edit, :destroy, :update]
  def index
    @bills = current_user.billboards
  end

  def show
  end

  def new
    @bill = current_user.billboards.new
    render :template => 'billboards/_form'
  end

  def create
    @bill = current_user.billboards.new(bill_params)

    if @bill.save
      redirect_to billboards_path
    else
      render :new
    end
  end
  
  def edit
    render :template => 'billboards/_form'
  end

  def update
    if @bill.update(bill_params)
      redirect_to billboard_path(@bill)
    else 
      render :edit
    end
  end

  def destroy
    @bill.destroy
    redirect_to billboards_path
  end

  private
  
  def set_billb
    @bill = current_user.billboards.find(params[:id])
  end

  def bill_params
    params.require(:billboard).permit(:billboard_name)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:update, :edit, :destroy, :show]
  

  def index
    @song = @art.songs
  end

  def show
  end

  def new
    @song = @art.songs.new
    render :template => "songs/_form"
  end

  def create
    @song = @art.songs.new(song_params)

    if @song.save
      redirect_to artist_path(@art)
    else
      render :new
    end
  end
  
  def edit
    render :template => "songs/_form"
  end

  def update
    if @song.update(song_params)
      redirect_to artist_path(@art)
    else
      render :edit 
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_path(@art)
  end

  private

  def set_artist
    @art = current_user.artists.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:song_title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @art.id ? "Edit Artist" : "Create New Artist" %></h1>
<hr />
<%= form_with( model: @art, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :artist_name %>
    <%= f.text_field :artist_name, required: true, placeholder: @art.artist_name, autofocus: true %>
    <%= f.submit class: "ui green button" %>
  </div>
<% end %>

<%= link_to 'Back', artists_path, class: "ui blue button" %>

app/views/artists/index.html.erb
<h1 class="ui header">Artists</h1>
<h3>Which artist would you like to browse?</h3>
<ol>
<% @arts.each do |artist| %>
<li><%= artist.artist_name %></li>
<%= link_to 'Edit Artist', edit_artist_path(artist), class: "ui blue button" %>
<%= link_to 'View Artist\'s Songs', artist_path(artist), class: "ui green button"  %>
<%= link_to 'Delete Artist', artist_path(artist), method: :delete, class: "ui red button"  %>
<% end %>
</ol>

<%= link_to 'Create New Artsit', new_artist_path, class: "ui blue button" %>

app/views/artists/show.html.erb
<h1 class="ui header"><%= @art.artist_name %></h1>
<ol>
  <%@art.songs.each do|song| %>
    <li><h3><%= song.song_title %></h3></li>
    <span>
      <%= link_to 'Edit Song Title', edit_artist_song_path(@art, song), class: "ui blue button"%> 
      <%= link_to 'Delete Song', artist_song_path(@art, song), method: :delete, class: "ui red button" %>
      <%= link_to 'Add Song To Billboard', artist_song_path(@art, song), class: "ui purple button" %>

    </span>
  <% end %>
</ol>
<%= link_to 'Create New Song', new_artist_song_path(@art), class: "ui green button" %>
<%= link_to 'Return', artists_path, class: "ui blue button" %>

app/views/billboards/_form.html.erb
<h1><%= @bill.id ? "Edit Billboard Title" : "Create New Billboard" %></h1>
<hr />
<%= form_with(model: @bill, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label "New Billboard Name"  %>
    <%= f.text_field :billboard_name , required: true, placeholder: "Billboard Name" %>
    <%= f.submit class: "ui button" %>
  </div>
<% end %>
<hr />
<%= link_to 'Return', billboards_path, class: "ui blue button"%>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<h3>Which billboard would you like to browse?</h3>

<ul>
    <% @bills.each do |billboard| %>
    <li><%=link_to billboard.billboard_name, billboard_path(billboard), class: "ui black button"%></li>
    <%= link_to "Edit Billboard", edit_billboard_path(billboard), class: "ui blue button"%>
    <%= link_to "Delete Billboard", billboard_path(billboard), method: :delete, class: "ui red button"%>
    <% end %>
</ul>
<%= link_to "Create Billboard", new_billboard_path, class: "ui green button"%>

app/views/billboards/show.html.erb
<h1 class="ui header"><%= @bill.billboard_name %></h1>

<h4>Still working on this...</h4>










<%# @songlist = [] %>

<%# 100.times do  %>
    <%#@songlist << Song.find(rand(1..1250)) %>
<%# end %>

<ol>
  <%# @songlist.each do |song| %>
    <li><%#song.song_title  %> by <%# Artist.find(song.artist_id).artist_name %></li>
  <%#end %>
</ol>

app/views/layouts/_navbar.html.erb
<span>
<%= link_to 'Billboards', billboards_path, class: "ui green inverted button" %>
<%= link_to 'Artists', artists_path, class: "ui blue inverted button" %>
<%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "ui red inverted button" %>
</span>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="ui container">
      <%= render 'layouts/navbar' %> 
      <%= yield %>
    </div>  
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? "Edit Song Title" : "Create New Song" %></h1>
<hr />
<%= form_with(model: [@art, @song], local: true, class: "ui form") do |f|%>
  <div class="field">
    <%= f.label :song_title %>
    <%= f.text_field :song_title, required: true, placeholder: @song.song_title, autofocus: true %>
    <%= f.submit class:"ui green button" %>
  </div>
<% end %>

<%= link_to 'Back', artist_songs_path(@art), class: "ui blue button" %>